### PR TITLE
[WAS-524] Upgraded EKS kubernetes version to 1.23

### PR DESCRIPTION
**Pull request by cenkawolfram**
I applied updates for upgrading 1.22 to 1.23.

Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1220

* Updated some of the fields in setup script
* Updated HorizontalPodAutoscaler api version(`autoscaling/v2beta2` to `autoscaling/v2`)
* Upgraded cluster version `1.22` to `1.23`

### CODE REVIEW

**Comment by cenkawolfram** [comment]
> @cenkawolfram We had some releases after this PR was created. Could you please merge the latest master with this PR

merged from master

**Review by manjuchandrika — CHANGES_REQUESTED** [review]
The cluster got deleted while running tear down script, but got the below error: Please check once before merging if this is going to be an issue;


Cleaning Configuration - Resetting Back To Default                      [  ✔  ]
fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted.
fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted.

Deleted EKS Cluster and Wolfram Application Server. Our warmest appreciation to you for running Wolfram Application Server on the Amazon environment. Thank You!

**Comment by cenkawolfram** [comment]
I could be able to run remove script after removing unnecessary s3 commands.
```
  Welcome to the Wolfram Application Server AWS Setup Manager, version 3.1.4


  Should any step fail the script shall halt. Completion of each step will be shown in green.

  Anytime you can re-run this script with --help flag to see available options.


☑□□□□ Phase 1 of 5: Prequisites Checks
Checking Kubectl Installed                                              [  ✔  ]
Checking Terraform Installed                                            [  ✔  ]
Checking Helm Installed                                                 [  ✔  ]
Checking AWS credentials                                                [  ✔  ]
Checking EKS Status                                                     [  ✔  ]

☑☑□□□ Phase 2 of 5: Delete Wolfram Application Server Deployments
Updating kubeconfig                                                     [  ✔  ]
Switching Context                                                       [  ✔  ]
Deleting Deployments                                                    [  ✔  ]
Deleting Kafka Cluster                                                  [  ✔  ]
Deleting NGINX Auth                                                     [  ✔  ]
Deleting Ingress                                                        [  ✔  ]
Deleting Horizontal Pod Autoscaler                                      [  ✔  ]
Deleting Services                                                       [  ✔  ]
Deleting Persistent Volume Claims                                       [  ✔  ]
Deleting Kafka Cluster Operator                                         [  ✔  ]
Deleting WAS Namespace                                                  [  ✔  ]
Reset Namespace                                                         [  ✔  ]

☑☑☑□□ Phase 3 of 5: Delete Dependencies
Deleting Ingress Controller                                             [  ✔  ]
Deleting Metrics Server                                                 [  ✔  ]
Deleting Cluster Autoscaler                                             [  ✔  ]
Deleting all namespace resources                                        [  ✔  ]
Deleting EFS Storage System                                             [  ✔  ]

☑☑☑☑□ Phase 4 of 5: Delete Amazon Kubernetes Cluster (EKS)
Deleting EKS                                                            [  ✔  ]

☑☑☑☑☑ Phase 5 of 5: Cleanup
Deleting Terraform S3 Bucket                                            [  ✔  ]
Deleting Dynamodb Terraform Table                                       [  ✔  ]
Cleaning Configuration - Resetting Back To Default                      [  ✔  ]

Deleted EKS Cluster and Wolfram Application Server. Our warmest appreciation to you for running Wolfram Application Server on Amazon environment. Thank You!

```

**Comment by manjuchandrika** [comment]
We need to change the WAS version as well. https://github.com/WolframResearch/WAS-Kubernetes/blob/cenka/upgrade-aws-1-23/EnvironmentSetup/AWS/Source/setup#L362 
It is currently 3.1.4. But after merging we will be releasing a new version based on the current version. As we have Kubernetes minor version change I think we can change our WAS version to 3.3.0 or do you prefer 3.2.1 instead?

**Review by manjuchandrika — APPROVED** [review]

**Pull request merged**
