### PR TITLE
[WAS-580/WAS-575] - Upgraded strimzi AWS

### PR DESCRIPTION
**Pull request by cenkawolfram**
* Upgraded strimzi version from 0.23 to 0.29
* Upgraded kafka version from 2.8.0 to 3.0.0
* Upgraded kubernetes version 1.24 to 1.25
* Saving credentials was not working except us-east-1 location. Fixed saveCredsFunction

### CODE REVIEW

**Review by delaix — APPROVED** [review]

**Review by hussainadev — CHANGES_REQUESTED** [review]
Kindly review your Azure PR and replicate required changes.

**Comment by manjuchandrika** [comment]
Script failing while testing the PR. We need to fix this.

☑□□□□ Phase 1 of 5: Prequisites Checks
Checking AWS credentials                                                [  ✔  ]
Checking Kubectl Installed                                              [  ✔  ]
Checking Terraform Installed                                            [  ✔  ]
Checking Helm Installed                                                 [  ✔  ]
Checking EKS Status                                                     [  ✔  ]

☑☑□□□ Phase 2 of 5: Build Amazon Kubernetes Cluster (EKS)
Creating Bucket for terraform                                           [  ✔  ]
Building EKS - (can take upto 30 minutes)                               [ERROR] Failed with error: 1
[  ✘  ]

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
╷
│ Error: Backend configuration changed
│ 
│ A change in the backend configuration has been detected, which may require
│ migrating existing state.
│ 
│ If you wish to attempt automatic migration of the state, use "terraform
│ init -migrate-state".
│ If you wish to store the current configuration with no changes to the
│ state, use "terraform init -reconfigure".
╵

Building EKS - (can take upto 30 minutes): [2023-08-16 17:53:21 UTC] [ERROR] Failed with error: 1
[2023-08-16 17:53:21 UTC] [ERROR] Something went wrong. Exiting.
[2023-08-16 17:53:21 UTC] [ERROR] The last few log entries were:

**Comment by hussainadev** [comment]
Hi @manjuchandrika 

Are you running a fresh build or running on an existing build?

**Comment by cenkawolfram** [comment]
_Error: Backend configuration changed_ issue is covered in Troubleshooting section. Please make sure that you killed the container on your local and follow these steps.
https://github.com/WolframResearch/WAS-Kubernetes/blob/master/EnvironmentSetup/AWS/README.md#troubleshooting

**Comment by manjuchandrika** [comment]
> Hi @manjuchandrika
> 
> Are you running a fresh build or running on an existing build?

Hello @hussainadev , happy to see your comment on this PR. It's a fresh build using this branch.

**Review by manjuchandrika — APPROVED** [review]
Tested. Looks good

**Review by hussainadev — APPROVED** [review]

**Pull request merged**
