### PR TITLE
[WAS-518] - Updated AWS setup script

### PR DESCRIPTION
**Pull request by cenkawolfram**
I updated the setup script. Previously we were storing the WAS details on local files. I added an S3 bucket to store values for `--delete` operation. 
* Upgraded Dockerfile/kubectl version to 1.24
* Added an S3 bucket as <CLUSTER_NAME>-creds-<ACCOUNT_ID>
It stores
```
GET_CLUSTER_NAME
GET_REGION
TERRAFORM_BUCKET
MINIO_ACCESS_KEY
MINIO_SECRET_KEY
DYNAMODB_TABLE:
EFS_FS_ID
RESOURCE_INFO_BUCKET
NODE_FILES_BUCKET
BASE_URL
RESOURCE_MANAGER_URL
NODEFILES_MANAGER_URL
ENDPOINT_MANAGER_URL
ENDPOINT_INFO_URL
RESTART_URL
```

values.

* Added an option for the script as `--get-creds` to check the current values.

### CODE REVIEW

**Review by manjuchandrika — COMMENTED** [review]
Cenk, after you have fixed the delete script. The script run fine. 
I got below messages
☑□□□□ Phase 1 of 5: Prequisites Checks
Checking Kubectl Installed                                              [  ✔  ]
Checking Terraform Installed                                            [  ✔  ]
Checking Helm Installed                                                 [  ✔  ]
Checking AWS credentials                                                [  ✔  ]
Checking EKS Status                                                     [  ✔  ]

☑☑□□□ Phase 2 of 5: Delete Wolfram Application Server Deployments
Updating kubeconfig                                                     [  ✔  ]
Switching Context                                                       [  ✔  ]
Deleting Deployments                                                    [  ✔  ]
Deleting Kafka Cluster                                                  [  ✔  ]
Deleting NGINX Auth                                                     [  ✔  ]
Deleting Ingress                                                        [  ✔  ]
Deleting Horizontal Pod Autoscaler                                      [  ✔  ]
Deleting Services                                                       [  ✔  ]
Deleting Persistent Volume Claims                                       [  ✔  ]
Deleting Kafka Cluster Operator                                         [  ✔  ]
Deleting WAS Namespace                                                  [  ✔  ]
Reset Namespace                                                         [  ✔  ]

☑☑☑□□ Phase 3 of 5: Delete Dependencies
Deleting Ingress Controller                                             [  ✔  ]
Deleting Metrics Server                                                 [  ✔  ]
Deleting Cluster Autoscaler                                             [  ✔  ]
Deleting all namespace resources                                        [  ✔  ]
Deleting EFS Storage System                                             [  ✔  ]

☑☑☑☑□ Phase 4 of 5: Delete Amazon Kubernetes Cluster (EKS)
Deleting EKS                                                            [  ✔  ]

☑☑☑☑☑ Phase 5 of 5: Cleanup
Deleting Terraform S3 Bucket                                            [  ✔  ]
Deleting Dynamodb Terraform Table                                       [  ✔  ]
Cleaning Configuration - Resetting Back To Default                      [  ✔  ]
setup: line 1151: remove-creds=delete:: command not found

Deleted EKS Cluster and Wolfram Application Server. Our warmest appreciation to you for running Wolfram Application Server on Amazon environment. Thank You!



But when I logged in I can see WAS cluster active on AWS EKS. But pods are all gone. Can you check that please.
Also there is an error in setup below line
setup: line 1151: remove-creds=delete:: command not found

**Comment by cenkawolfram** [comment]
I couldn't reproduce EKS removing issue but it seems there is no error in the script now.
```
☑☑☑□□ Phase 3 of 5: Delete Dependencies
Deleting Ingress Controller                                             [  ✔  ]
Deleting Metrics Server                                                 [  ✔  ]
Deleting Cluster Autoscaler                                             [  ✔  ]
Deleting all namespace resources                                        [  ✔  ]
Deleting EFS Storage System                                             [  ✔  ]

☑☑☑☑□ Phase 4 of 5: Delete Amazon Kubernetes Cluster (EKS)
Deleting EKS                                                            [  ✔  ]

☑☑☑☑☑ Phase 5 of 5: Cleanup
Deleting Terraform S3 Bucket                                            [  ✔  ]
Deleting Dynamodb Terraform Table                                       [  ✔  ]
Cleaning Configuration - Resetting Back To Default                      [  ✔  ]

Deleted EKS Cluster and Wolfram Application Server. Our warmest appreciation to you for running Wolfram Application Server on Amazon environment. Thank You!

[sudo] password for cenka: 
```

**Comment by manjuchandrika** [comment]
This is tested. Good to go.

**Comment by manjuchandrika** [comment]
Merging this pull request as these changes are released along with the 3.1.4 version

**Pull request merged**
